- name: Install requirements
  local_action: command ansible-galaxy install -r '{{ role_path }}/requirements.yml'
  become: no
  changed_when: false
- name: Install watchdog
  include_role:
    name: whiskerlabs.watchdog
  vars:
    watchdog_ping_addrs:
      - "{{ ansible_default_ipv4['gateway'] }}"
