---
- name: Install dependencies
  apt:
    pkg:
      - lxc
      - python3-lxc
    update_cache: yes
- name: Configure lxc-net bridge
  lineinfile:
    regex: USE_LXC_BRIDGE=
    line: USE_LXC_BRIDGE="{{ 'false' if bridge_ports else 'true' }}"
    path: /etc/default/lxc-net
- name: Delete lxc host bridge
  file:
    path: /etc/network/interfaces.d/lxc
    state: absent
  register: delete_lxc_host_bridge
  when: not bridge_ports
- name: Create lxc host bridge
  copy:
    content: |
      auto lxcbr0
      iface lxcbr0 inet dhcp
        bridge_ports {{ bridge_ports | join(' ') }}
        bridge_stp 0
        bridge_fd 0
        bridge_maxwait 0
    dest: /etc/network/interfaces.d/lxc
  register: create_lxc_host_bridge
  when: bridge_ports
- name: Check if dhcpcd config exists
  stat:
    path: /etc/dhcpcd.conf
  register: dhcpcd_conf
- name: Exclude interfaces from dhcpcd
  lineinfile:
    regex: denyinterfaces
    insertafter: '^ *#.*dhcpcd\.conf\(5\)'
    firstmatch: yes
    line: denyinterfaces {{ bridge_ports | join(' ') }} lxcbr0
    path: /etc/dhcpcd.conf
  register: dhcpcd_conf
  when: bridge_ports and dhcpcd_conf.stat.exists
- name: Restart dhcpcd
  service:
    name: dhcpcd
    state: restarted
  when: dhcpcd_conf.changed
- name: Restart network
  service:
    name: networking
    state: restarted
  when: delete_lxc_host_bridge.changed or create_lxc_host_bridge.changed
