---
- name: Install dependencies
  ansible.builtin.package:
    name: 
      - lxc
      - "{{ 'lxc-download' if ansible_facts['os_family'] == 'Alpine' else 'lxc' }}"
      - "{{ 'py3-lxc' if ansible_facts['os_family'] == 'Alpine' else 'python3-lxc' }}"
- name: Configure lxc-net bridge
  lineinfile:
    regex: USE_LXC_BRIDGE=
    line: USE_LXC_BRIDGE="{{ 'false' if bridge_ports else 'true' }}"
    path: /etc/default/lxc-net
    create: true
- name: Delete LXC host bridge
  file:
    path: /etc/network/interfaces.d/lxc
    state: absent
  register: delete_lxc_host_bridge
  when: bridge_ports is not defined
- name: Create network interfaces directory
  ansible.builtin.file:
    path: /etc/network/interfaces.d
    state: directory
- name: Disable bridge port interfaces
  replace:
    dest: /etc/network/interfaces
    regexp: '^auto {{ item }}'
    replace: '#auto {{ item }}'
  loop: '{{ bridge_ports }}'
  when: bridge_ports is defined
- name: Disable bridge port interfaces
  replace:
    dest: /etc/network/interfaces
    regexp: '^iface {{ item }} '
    replace: '#iface {{ item }} '
  loop: '{{ bridge_ports }}'
  when: bridge_ports is defined
- name: Create LXC host bridge
  copy:
    content: |
      auto lxcbr0
      iface lxcbr0 inet dhcp
        bridge_ports {{ bridge_ports | join(' ') }}
        bridge_stp 0
        bridge_fd 0
        bridge_maxwait 0
    dest: /etc/network/interfaces.d/lxc
  register: create_lxc_host_bridge
  when: bridge_ports is defined
- name: Source LXC interfaces
  lineinfile:
    line: source /etc/network/interfaces.d/lxc
    path: /etc/network/interfaces
  when: ansible_facts['os_family'] == 'Alpine'
- name: Check if dhcpcd config exists
  stat:
    path: /etc/dhcpcd.conf
  register: dhcpcd_conf
- name: Exclude interfaces from dhcpcd
  lineinfile:
    regex: denyinterfaces
    insertafter: '^ *#.*dhcpcd\.conf\(5\)'
    firstmatch: yes
    line: denyinterfaces {{ bridge_ports | join(' ') }} lxcbr0
    path: /etc/dhcpcd.conf
  register: dhcpcd_conf
  when: bridge_ports is defined and dhcpcd_conf.stat.exists
- name: Restart dhcpcd
  service:
    name: dhcpcd
    state: restarted
  when: dhcpcd_conf.changed
- name: Restart network
  service:
    name: networking
    state: restarted
  when: delete_lxc_host_bridge.changed or create_lxc_host_bridge.changed
- name: Enable lxc service
  ansible.builtin.service:
    name: lxc
    enabled: true
    state: started
